apiVersion: v1
kind: Service
metadata:
  name: argocd-helloworld-title1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    app: argocd-helloworld
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '
events {
}
http {
  server {
    listen 80;
    location / {
      return 200 "Hello, world!!!!";
    }
  }
}
'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-helloworld-title2
spec:
  selector:
    matchLabels:
      app: argocd-helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-helloworld
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: config-vol
            mountPath: /etc/nginx/
      volumes:
        - name: config-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
